<a href="https://colab.research.google.com/github/NidhiSingh25901/PytorchWithDeepLearning/blob/main/1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello! I am excited to learn Python Programming Language")

Hello! I am excited to learn Python Programming Language


In [2]:
!nvidia-smi

Sun Nov  9 05:45:28 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [11]:
#Introduction to tensor - tensor is a way to represent numeric data
# Pytorch tensor is creates using torch.tensor()

#creating scalar using tensor
scalar = torch.tensor(7)
scalar


tensor(7)

In [12]:
scalar.ndim

0

In [13]:
scalar.item()

7

In [15]:
#Creating vector using tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
#matrix using tensor
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
matrix.ndim

2

In [25]:
matrix[1]

tensor([ 9, 10])

In [23]:
matrix.shape

torch.Size([2, 2])

In [26]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5,],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [27]:
tensor.ndim

3

In [28]:
tensor.shape

torch.Size([1, 3, 3])

In [30]:
#creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3660, 0.2867, 0.9171, 0.4563],
        [0.0834, 0.7682, 0.2273, 0.9121],
        [0.8748, 0.1332, 0.6220, 0.5666]])

In [31]:
random_tensor.ndim

2