<a href="https://colab.research.google.com/github/NidhiSingh25901/PytorchWithDeepLearning/blob/main/Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np

array = np.arange(1.0,8.0)

tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [7]:
tensor.dtype

torch.float64

In [8]:
torch.arange(1.0,8.0).dtype

torch.float32

In [12]:
array = array+1
array

array([ 5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
tensor= tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [18]:
#Reproducibility (trying to take remote out of random)
random1 = torch.rand(3,4)

In [19]:
random2 = torch.rand(3,4)

In [20]:
random1 == random2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
import torch

In [23]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C == random_tensor_D


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
#Running tensors and pytorch objects on the GPUS
