<a href="https://colab.research.google.com/github/NidhiSingh25901/PytorchWithDeepLearning/blob/main/TorchMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Multiplication of tensors using Pytorch

In [2]:
import torch

In [3]:
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2)

tensor(0.0383)

In [8]:
tensor3 = torch.tensor([[1,2,3],[3,4,5]])
tensor4 = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
val = torch.matmul(tensor3, tensor4)
val

tensor([[22, 28],
        [40, 52]])

In [9]:
val.ndim

2

In [11]:
val.shape

torch.Size([2, 2])

In [12]:
tensor5 = torch.tensor([[1,2,3],[3,4,5]])
tensor5.T

tensor([[1, 3],
        [2, 4],
        [3, 5]])

In [14]:
tensor6 = torch.tensor(([1,2],[3,4],[4,5]))
tensor6.T

tensor([[1, 3, 4],
        [2, 4, 5]])

In [15]:
torch.matmul(tensor5.T, tensor6.T)

tensor([[ 7, 15, 19],
        [10, 22, 28],
        [13, 29, 37]])